Category and Relevance Classifier
idmc-labs/idetect pull request #5
Opened 2017-07-26 14:06 UTC by georgerichardson

- Downloads pretrained models from S3 bucket
- Contains all of the custom transformers and estimators needed
- If article is found to be relevant, calls `extract_reports` from `fact_extractor.py`

2017-07-27 02:17 UTC, WanderingStar requested changes

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +            category = 'disaster'
Returning a successful value in an error case strikes me as dangerous. What if there's a transient error that would be fixed by re-running? It seems like it would be better to let this exception bubble up and cause the Worker to mark this as failed, or to explicitly set a marker value that alerts a user to the fact that this failed.

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +        tokens = [t.lower() for t in tokens]
Should this happen before the stop_words check? Are stop words intended to be case-sensitive?

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +            else:
What happens if several workers are started simultaneously, and they all check to see if the model is present, determine that it is not, and start downloading it? You're not locking the file that you're writing to below, so it's possible that the downloads will attempt to write at the same time and corrupt the file. Another possible failure is that one worker starts before another and starts downloading the file, and the other sees that the file exists and tries to read the only-partially-downloaded file.

Ideas:
1. Download to a tempfile (use the `tempfile` module, rather than a fixed file name for the same simultaneous write reason) and then move the file into place (`os.rename` is an atomic operation).
* Pros: easy to implement
* Cons: could be wasteful, as several downloads could take place
2. Lock the destination file on the filesystem. Note that you need to open the file and attempt to lock it this way before trying to read from it (the `load` case) as well as write it. It probably makes sense to do it first, and catch the file not found error in the case that it doesn't exist yet. 
```
import fcntl
... make sure the directory exists ...
with open(default_model_path, 'wb+') as f:
    try:
       fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB) # exclusive, nonblocking lock
       ... check if the file is empty, if not, someone else has already finished downloading it ...
       ... download and write the file ...
    catch BlockingIOError:
        # this happens if someone else is currently downloading it
        fcntl.flock(f, fcntl.LOCK_EX)  # exclusive, *blocking* lock. will wait until the other lock is released
    ...
    finally:
        fcntl.flock(x, fcntl.LOCK_UN) # probably not actually necessary because closing the filehandle will release the lock... I think.
```
* Pros: not wasteful
* Cons: trickier to implement correctly

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +    def tfidf_transform(texts, dictionary=None, tfidf_model=None):
Does this get called from anywhere? Why does it take dictionary as a parameter, rather than using `self.dictionary`?

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +        self.corpus_tfidf, self.dictionary = self.build_tfidf(texts)
Will these ever be used again? I think they could just be local variables, rather than instance properties.

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +        if not self.lsi_model:
Do you want to do this check _before_ calling `self.build_tfidf`? Is there value in calling that after there is already an LSI model?

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +        return self
I don't think you need to return anything here. The caller must already have `self`, since it called a method on it.

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/category/category.py
> +        return self
I think it's also a bit confusing that some of the `make_` methods return the thing they just made and others of them change the object. Should the mutators be called `set_tfidf_model`?

Also, it's surprising that a second call to `make_tfidf_model` with a different corpus silently does nothing. I would expect it to either replace the existing tfidf_model or to raise an exception to let the caller know that what they just tried didn't happen.

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/relevance/relevance.py
> +        if model_path and os.path.isfile(model_path):
This would make a great library function, so the code doesn't get repeated.

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/relevance/relevance.py
> +class Tokenizer(TransformerMixin):
Can this be declared in one place and imported here and in `category.py`?

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/relevance/relevance.py
> +        stems = [s for s in stems if not s.isdigit()]
Does `self.stemmer.stem(t)` return digits for tokens that weren't `isdigit()` to begin with? Maybe "1000s" => "1000"?

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/relevance/relevance.py
> +        if model_path and os.path.isfile(model_path):
Or RelevanceModel and CategoryModel could both be instances of class DownloadableModel initialized with different `model_path` and `url` values.

2017-07-27 02:17 UTC, WanderingStar commented on source/python/idetect/nlp_models/relevance/relevance.py
> +class Tokenizer(TransformerMixin):
Generally, I think we should repeat as little code as possible. If we find a bug in Tokenizer, we don't want to have to make sure to fix it in both places.

2017-07-27 02:19 UTC, WanderingStar commented
Most of my comments are stylistic/DRY/optimizations, but I think the one about locking and the one about returning a non-error value in the case that an error occurs should be addressed.

2017-07-30 18:05 UTC, georgerichardson commented on source/python/idetect/nlp_models/category/category.py
> +        tokens = [t.lower() for t in tokens]
Yep, that's right. Swapped it.

2017-07-30 18:06 UTC, georgerichardson commented on source/python/idetect/nlp_models/category/category.py
> +    def tfidf_transform(texts, dictionary=None, tfidf_model=None):
It was getting called in the LSI Transformer, but was unnecessary. Have removed.

2017-07-30 18:06 UTC, georgerichardson commented on source/python/idetect/nlp_models/category/category.py
> +        return self
Think I've got most of these.

2017-07-30 18:07 UTC, georgerichardson commented on source/python/idetect/nlp_models/category/category.py
> +        self.corpus_tfidf, self.dictionary = self.build_tfidf(texts)
These were a hangover from when I was testing the models, so I could inspect the attributes. Removed `self.corpus_tfidf`, but the dictionary does get used again.

2017-07-30 18:07 UTC, georgerichardson commented on source/python/idetect/nlp_models/category/category.py
> +        if not self.lsi_model:
I actually removed this completely, it was just to accommodate a shortcut I was using when building models a while back.

2017-07-30 18:08 UTC, georgerichardson commented on source/python/idetect/nlp_models/relevance/relevance.py
> +        if model_path and os.path.isfile(model_path):
Made a base class `DownloadableModel`.

2017-07-30 18:09 UTC, georgerichardson commented on source/python/idetect/nlp_models/relevance/relevance.py
> +class Tokenizer(TransformerMixin):
Agree with this. Have a couple of thoughts to discuss on better ways to do it for the next PR.

2017-07-30 18:09 UTC, georgerichardson commented on source/python/idetect/nlp_models/relevance/relevance.py
> +        stems = [s for s in stems if not s.isdigit()]
Yeah, the stemmer does remove any characters appended to digits.

2017-07-30 18:10 UTC, georgerichardson commented
Tried to address most of the comments above, but there's a few larger points I'll get a second opinion on in Slack before changing.

2017-07-30 19:32 UTC, WanderingStar commented on source/python/idetect/nlp_models/base_model.py
> +                    except OSError as exc:  # Guard against rare condition
"race" condition?

2017-07-30 19:33 UTC, WanderingStar commented on source/python/idetect/nlp_models/base_model.py
> +                            if chunk:  # filter out keep-alive new chunks
Out of curiosity, what happens if you call `f.write(chunk)` with an empty chunk?

2017-07-30 19:36 UTC, WanderingStar commented on source/python/idetect/nlp_models/base_model.py
> +                        model = joblib.load(model_path)
What happens in the else case here? What should happen? I assume we should download the model, right? Could you `return model` here and move the `else:` case of `if os.path.isfile(model_path):`, to the top level?

2017-07-30 19:38 UTC, WanderingStar commented on source/notebooks/file_download.ipynb
> +    {
Would this be removed if we cleared the output in Jupyter?

2017-07-30 19:40 UTC, WanderingStar commented
The locking logic looks pretty solid. It's the kind of thing I'd have to unit test to be sure of the edge cases, but I assume it generally works?

2017-07-30 19:44 UTC, WanderingStar approved these changes

2017-07-31 01:16 UTC, simonb83 reviewed
Just to understand how it will all fit together, which method will the Classification worker use?

2017-08-02 05:30 UTC, merged